In [1]:
import numpy as np

In [6]:
arr=np.array([[1,2,3],[4,5,6]])

print(arr)
type(arr)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [8]:
arr.ndim, arr.shape, arr.size, arr.dtype

(2, (2, 3), 6, dtype('int32'))

In [10]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='float') # array created using passed list
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [20]:
o=np.ones((3,4))
print(o, '\n')
z=np.zeros((3,4))
print(z)

np.eye(3) # identity matrix

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
f=np.arange(0,100,10)
f

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
g=np.linspace(0,5,10)
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

print(arr)
arr.reshape((2,2,3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
arr=np.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])

arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [31]:
arr[1::2, :3:2]

array([[4., 6.],
       [3., 4.]])

In [32]:
a=np.array([1,2,5,3])
a

array([1, 2, 5, 3])

In [33]:
a+1

array([2, 3, 6, 4])

In [34]:
a*3

array([ 3,  6, 15,  9])

In [35]:
arr=np.array([[1,5,6],[4,7,2],[3,1,9]])
arr

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 9]])

In [45]:
arr.max(), arr.max(axis=1), arr.max(axis=0) # same for min

(9, array([6, 7, 9]), array([4, 7, 9]))

In [51]:
arr.sum(), arr.cumsum(), arr.cumsum(axis=0), arr.cumsum(axis=1)

(38,
 array([ 1,  6, 12, 16, 23, 25, 28, 29, 38]),
 array([[ 1,  5,  6],
        [ 5, 12,  8],
        [ 8, 13, 17]]),
 array([[ 1,  6, 12],
        [ 4, 11, 13],
        [ 3,  4, 13]]))

In [52]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[4 3]
 [2 1]]


In [53]:
a+b

array([[5, 5],
       [5, 5]])

In [54]:
a*b

array([[4, 6],
       [6, 4]])

In [55]:
a.dot(b)

array([[ 8,  5],
       [20, 13]])

In [56]:
a=np.array([0, np.pi/2, np.pi])
print(np.sin(a))
e=np.array([0,1,2,3])
print(np.exp(e))
print(np.sqrt(e))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]


In [57]:
a=np.array([[4,2,3],[7,5,1],[9,6,8]])
a

array([[4, 2, 3],
       [7, 5, 1],
       [9, 6, 8]])

In [58]:
np.sort(a)

array([[2, 3, 4],
       [1, 5, 7],
       [6, 8, 9]])

In [59]:
np.sort(a, axis=1)

array([[2, 3, 4],
       [1, 5, 7],
       [6, 8, 9]])

In [61]:
np.sort(a, axis=0, kind='mergesort')

array([[4, 2, 1],
       [7, 5, 3],
       [9, 6, 8]])

In [62]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[4 3]
 [2 1]]


In [64]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [65]:
np.hstack((a,b))

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [66]:
c=[5,6]
np.column_stack((a,c))

array([[1, 2, 5],
       [3, 4, 6]])

In [68]:
a=np.array([[1,2,3,4,5,6],
           [7,8,9,10,11,12]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [72]:
np.hsplit(a,2)

[array([[1, 2, 3],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [10, 11, 12]])]

In [74]:
np.vsplit(a,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]